package ac.at.tuwien.ifs.sepses.vocab;/* CVS $Id: $ */

import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.rdf.model.Property;
import org.apache.jena.rdf.model.Resource;

/**
 * Vocabulary definitions from file:/Users/juang/CodeRepo/Sepses/cyber-kb/src/main/resources/owl/CAPEC.ttl 
 * @author Auto-generated by schemagen on 09 Apr 2019 09:07 
 */
public class CAPEC {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://w3id.org/sepses/vocab/ref/capec#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property ABSTRACTION = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#abstraction" );
    
    public static final Property ATTACK_STEP = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#attackStep" );
    
    public static final Property ATTACK_STEP_DESCRIPTION = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#attackStepDescription" );
    
    public static final Property ATTACK_STEP_PHASE = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#attackStepPhase" );
    
    public static final Property ATTACK_STEP_TECHNIQUE = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#attackStepTechnique" );
    
    public static final Property CONSEQUENCE_IMPACT = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#consequenceImpact" );
    
    public static final Property CONSEQUENCE_SCOPE = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#consequenceScope" );
    
    public static final Property DESCRIPTION = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#description" );
    
    public static final Property HAS_CONSEQUENCE = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#hasConsequence" );
    
    public static final Property HAS_EXECUTION_FLOW = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#hasExecutionFlow" );
    
    public static final Property HAS_MITIGATION = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#hasMitigation" );
    
    public static final Property HAS_REFERENCE = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#hasReference" );
    
    public static final Property HAS_RELATED_ATTACK_PATTERN = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#hasRelatedAttackPattern" );
    
    public static final Property HAS_RELATED_WEAKNESS = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#hasRelatedWeakness" );
    
    public static final Property HAS_SKILL_REQUIRED = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#hasSkillRequired" );
    
    public static final Property HAS_SUBMISSION_HISTORY = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#hasSubmissionHistory" );
    
    public static final Property ID = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#id" );
    
    public static final Property LIKELIHOOD_OF_ATTACK = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#likelihoodOfAttack" );
    
    public static final Property NAME = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#name" );
    
    public static final Property PREREQUISITE = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#prerequisite" );
    
    public static final Property RELATED_ATTACK_PATTERN_NATURE = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#relatedAttackPatternNature" );
    
    public static final Property RELATED_ATTACK_PATTERN_VIEW_ID = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#relatedAttackPatternViewId" );
    
    public static final Property RELATED_CAPEC = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#relatedCAPEC" );
    
    public static final Property RESOURCE_REQUIRED = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#resourceRequired" );
    
    public static final Property SKILL_DESCRIPTION = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#skillDescription" );
    
    public static final Property SKILL_LEVEL = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#skillLevel" );
    
    public static final Property STATUS = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#status" );
    
    public static final Property TYPICAL_SEVERITY = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/capec#typicalSeverity" );
    
    public static final Resource CAPEC = m_model.createResource( "http://w3id.org/sepses/vocab/ref/capec#CAPEC" );
    
    public static final Resource CONSEQUENCE = m_model.createResource( "http://w3id.org/sepses/vocab/ref/capec#Consequence" );
    
    public static final Resource EXECUTION_FLOW = m_model.createResource( "http://w3id.org/sepses/vocab/ref/capec#ExecutionFlow" );
    
    public static final Resource MITIGATION = m_model.createResource( "http://w3id.org/sepses/vocab/ref/capec#Mitigation" );
    
    public static final Resource RELATED_ATTACK_PATTERN = m_model.createResource( "http://w3id.org/sepses/vocab/ref/capec#RelatedAttackPattern" );

    public static final Resource ATTACK_PATTERN_CATALOG = m_model.createResource( "http://w3id.org/sepses/vocab/ref/capec#AttackPatternCatalog" );
    
    public static final Resource RELATED_WEAKNESS = m_model.createResource( "http://w3id.org/sepses/vocab/ref/capec#RelatedWeakness" );
    
    public static final Resource SKILL_REQUIRED = m_model.createResource( "http://w3id.org/sepses/vocab/ref/capec#SkillRequired" );
    
}
