package ac.at.tuwien.ifs.sepses.vocab;/* CVS $Id: $ */

import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.rdf.model.Property;
import org.apache.jena.rdf.model.Resource;

/**
 * Vocabulary definitions from file:/Users/juang/CodeRepo/Sepses/cyber-kb/src/main/resources/owl/CPE.ttl
 *
 * @author Auto-generated by schemagen on 09 Apr 2019 09:07
 */
public class CPE {
    /**
     * <p>The namespace of the vocabulary as a string</p>
     */
    public static final String NS = "http://w3id.org/sepses/vocab/ref/cpe#";
    public static final String NS_INSTANCE = "http://w3id.org/sepses/resource/cpe/";
    /**
     * <p>The RDF model that holds the vocabulary terms</p>
     */
    private static Model m_model = ModelFactory.createDefaultModel();
    /**
     * <p>The namespace of the vocabulary as a resource</p>
     */
    public static final Resource NAMESPACE = m_model.createResource(NS);
    public static final Property CPE_VERSION =
            m_model.createProperty("http://w3id.org/sepses/vocab/ref/cpe#cpe_version");
    public static final Property EDITION = m_model.createProperty("http://w3id.org/sepses/vocab/ref/cpe#edition");
    public static final Property GENERATOR_TIME_STAMP =
            m_model.createProperty("http://w3id.org/sepses/vocab/ref/cpe#generatorTimeStamp");
    public static final Property HAS_LOGICAL_TEST =
            m_model.createProperty("http://w3id.org/sepses/vocab/ref/cpe#hasLogicalTest");
    public static final Property HAS_LOGICAL_TEST_FACT_REF =
            m_model.createProperty("http://w3id.org/sepses/vocab/ref/cpe#hasLogicalTestFactRef");
    public static final Property HAS_PRODUCT =
            m_model.createProperty("http://w3id.org/sepses/vocab/ref/cpe#hasProduct");
    public static final Property HAS_VENDOR =
            m_model.createProperty("http://w3id.org/sepses/vocab/ref/cpe#hasVendor");
    public static final Property LANGUAGE = m_model.createProperty("http://w3id.org/sepses/vocab/ref/cpe#language");
    public static final Property OTHER = m_model.createProperty("http://w3id.org/sepses/vocab/ref/cpe#other");
    public static final Property PART = m_model.createProperty("http://w3id.org/sepses/vocab/ref/cpe#part");
    public static final Property PRODUCT_NAME =
            m_model.createProperty("http://w3id.org/sepses/vocab/ref/cpe#productName");
    public static final Property SOFTWARE_EDITION =
            m_model.createProperty("http://w3id.org/sepses/vocab/ref/cpe#softwareEdition");
    public static final Property TARGET_HARDWARE =
            m_model.createProperty("http://w3id.org/sepses/vocab/ref/cpe#targetHardware");
    public static final Property TARGET_SOFTWARE =
            m_model.createProperty("http://w3id.org/sepses/vocab/ref/cpe#targetSoftware");
    public static final Property UPDATE = m_model.createProperty("http://w3id.org/sepses/vocab/ref/cpe#update");
    public static final Property VENDOR_NAME =
            m_model.createProperty("http://w3id.org/sepses/vocab/ref/cpe#vendorName");
    public static final Property VERSION = m_model.createProperty("http://w3id.org/sepses/vocab/ref/cpe#version");
    public static final Resource CPE = m_model.createResource("http://w3id.org/sepses/vocab/ref/cpe#CPE");
    public static final Resource LOGICAL_TEST =
            m_model.createResource("http://w3id.org/sepses/vocab/ref/cpe#LogicalTest");
    public static final Resource PRODUCT = m_model.createResource("http://w3id.org/sepses/vocab/ref/cpe#Product");
    public static final Resource VENDOR = m_model.createResource("http://w3id.org/sepses/vocab/ref/cpe#Vendor");

    /**
     * <p>The namespace of the vocabulary as a string</p>
     *
     * @see #NS
     */
    public static String getURI() {
        return NS;
    }

}
