package ac.at.tuwien.ifs.sepses.vocab;/* CVS $Id: $ */

import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.rdf.model.Property;
import org.apache.jena.rdf.model.Resource;

/**
 * Vocabulary definitions from file:/Users/juang/CodeRepo/Sepses/cyber-kb/src/main/resources/owl/CVE.ttl 
 * @author Auto-generated by schemagen on 09 Apr 2019 09:07 
 */
public class CVE {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://w3id.org/sepses/vocab/ref/cve#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property DATE_PUBLISHED = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/cve#datePublished" );
    
    public static final Property DESCRIPTION = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/cve#description" );
    
    public static final Property HAS_CPE = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/cve#hasCPE" );
    
    public static final Property HAS_CWE = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/cve#hasCWE" );
    
    public static final Property HAS_REFERENCE = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/cve#hasReference" );
    
    public static final Property HAS_VULNERABLE_CONFIGURATION = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/cve#hasVulnerableConfiguration" );
    
    public static final Property ID = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/cve#id" );
    
    public static final Property REFERENCE = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/cve#reference" );
    
    public static final Property REFERENCE_SOURCE = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/cve#referenceSource" );
    
    public static final Property REFERENCE_TYPE = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/cve#referenceType" );
    
    public static final Property REFERENCE_URL = m_model.createProperty( "http://w3id.org/sepses/vocab/ref/cve#referenceUrl" );
    
    public static final Resource CVE = m_model.createResource( "http://w3id.org/sepses/vocab/ref/cve#CVE" );
    
    public static final Resource REFERENCE_CLASS = m_model.createResource( "http://w3id.org/sepses/vocab/ref/cve#Reference" );
    
    public static final Resource VULNERABILITY = m_model.createResource( "http://w3id.org/sepses/vocab/ref/cve#Vulnerability" );
    
}
