package ac.at.tuwien.ifs.sepses.vocab;/* CVS $Id: $ */

import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.rdf.model.Property;
import org.apache.jena.rdf.model.Resource;

/**
 * Vocabulary definitions from file:/Users/juang/CodeRepo/Sepses/cyber-kb/src/main/resources/owl/CVSS.ttl
 *
 * @author Auto-generated by schemagen on 09 Apr 2019 09:07
 */
public class CVSS {
    /**
     * <p>The namespace of the vocabulary as a string</p>
     */
    public static final String NS = "http://w3id.org/sepses/vocab/ref/cvss#";
    public static final String NS_INSTANCE = "http://w3id.org/sepses/resource/cvss/";
    /**
     * <p>The RDF model that holds the vocabulary terms</p>
     */
    private static Model m_model = ModelFactory.createDefaultModel();
    /**
     * <p>The namespace of the vocabulary as a resource</p>
     */
    public static final Resource NAMESPACE = m_model.createResource(NS);
    public static final Property ACCESS_COMPLEXITY =
            m_model.createProperty("http://w3id.org/sepses/vocab/ref/cvss#accessComplexity");
    public static final Property ACCESS_VECTOR =
            m_model.createProperty("http://w3id.org/sepses/vocab/ref/cvss#accessVector");
    public static final Property ATTACK_COMPLEXITY =
            m_model.createProperty("http://w3id.org/sepses/vocab/ref/cvss#attackComplexity");
    public static final Property ATTACK_VECTOR =
            m_model.createProperty("http://w3id.org/sepses/vocab/ref/cvss#attackVector");
    public static final Property AUTHENTICATION =
            m_model.createProperty("http://w3id.org/sepses/vocab/ref/cvss#authentication");
    public static final Property AVAILABILITY_IMPACT =
            m_model.createProperty("http://w3id.org/sepses/vocab/ref/cvss#availabilityImpact");
    public static final Property BASE_SCORE =
            m_model.createProperty("http://w3id.org/sepses/vocab/ref/cvss#baseScore");
    public static final Property CONFIDENTIALITY_IMPACT =
            m_model.createProperty("http://w3id.org/sepses/vocab/ref/cvss#confidentialityImpact");
    public static final Property EXPLOITABILITY_SCORE =
            m_model.createProperty("http://w3id.org/sepses/vocab/ref/cvss#exploitabilityScore");
    public static final Property HAS_CVSS = m_model.createProperty("http://w3id.org/sepses/vocab/ref/cvss#hasCVSS");
    public static final Property IMPACT_SCORE =
            m_model.createProperty("http://w3id.org/sepses/vocab/ref/cvss#impactScore");
    public static final Property INTEGRITY_IMPACT =
            m_model.createProperty("http://w3id.org/sepses/vocab/ref/cvss#integrityImpact");
    public static final Property PRIVILEGES_REQUIRED =
            m_model.createProperty("http://w3id.org/sepses/vocab/ref/cvss#privilegesRequired");
    public static final Property SCOPE = m_model.createProperty("http://w3id.org/sepses/vocab/ref/cvss#scope");
    public static final Property USER_INTERACTION =
            m_model.createProperty("http://w3id.org/sepses/vocab/ref/cvss#userInteraction");
    public static final Property VECTOR_STRING =
            m_model.createProperty("http://w3id.org/sepses/vocab/ref/cvss#vectorString");
    public static final Resource CVSS = m_model.createResource("http://w3id.org/sepses/vocab/ref/cvss#CVSS");
    public static final Resource CVSSBASE_METRIC =
            m_model.createResource("http://w3id.org/sepses/vocab/ref/cvss#CVSSBaseMetric");
    public static final Resource CVSSBASE_METRIC_V2 =
            m_model.createResource("http://w3id.org/sepses/vocab/ref/cvss#CVSSBaseMetricV2");
    public static final Resource CVSSBASE_METRIC_V3 =
            m_model.createResource("http://w3id.org/sepses/vocab/ref/cvss#CVSSBaseMetricV3");

    /**
     * <p>The namespace of the vocabulary as a string</p>
     *
     * @see #NS
     */
    public static String getURI() {
        return NS;
    }

}
